config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'dashboard#index'
  resources :customers, only: :index

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  def self.search_keyword(keyword)
    keyword.downcase!
    if keyword.include?('@')
      self.where('email ILIKE ?', "%#{keyword}%").order(email: :desc, last_name: :asc)
    else
      self.where('first_name ILIKE ? OR
                  last_name  ILIKE ?', "%#{keyword}%", "%#{keyword}%").order(email: :desc, last_name: :asc)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    if params[:keywords].present?
      @keywords = params[:keywords]
      @customers = Customer.search_keyword(@keywords).page(params[:page]).per(10)
    else
      @customers = []
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/customers/index.html.erb
<header>
  <h2>Customer Search</h2>
</header>

<section class="search-form">
  <%= form_for :customers, method: :get do |f| %>
      <div class="input-group">
        <%= label_tag :keywords, nil, class: 'sr-only' %>
        <%= text_field_tag :keywords, nil, placeholder: 'First Name, Last Name or Email Address', class: 'form-control input' %>
        <span class="input-group-btn">
          <%= submit_tag 'Find Customers', class: 'btn btn-primary' %>
        </span>
      </div>
  <% end %>
</section>

<section class="search-results">
  <header>
    <h3>Results</h3>
  </header>
  <ol class="list-group">
    <% @customers.each do |customer| %>
        <li class="list-group-item clear-fix">
          <h3 class="pull-right">
            <small>Joined</small> <%= customer.created_at.to_date %>
          </h3>
          <h3>
            <%= customer.first_name %><%= customer.last_name %> <small><%= customer.username %></small>
          </h3>
          <h4><%= customer.email %></h4>
        </li>
    <% end %>
  </ol>
</section>

<%= paginate @customers if @customers.present? %>

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

<h1>Your email is <%= current_user.email %></h1>

<%= link_to 'Customer', customers_path %>
<%= link_to 'Log Out', destroy_user_session_path, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shine</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag *webpack_asset_paths('application') %>
  </head>

  <body class="container">
    <% if notice.present? %>
        <aside class="alert alert-info">
          <%= notice %>
        </aside>
    <% end %>
    <% if alert.present? %>
        <aside class="alert alert-danger">
          <%= alert %>
        </aside>
    <% end %>
    <%= yield %>
  </body>
</html>